### ISSUE TITLE
Certificate Verify Failed

### ISSUE THREAD

**Issue by FriedrichFroebel** [steve8x8/geotoad#328]
I get an error message when trying to get the data (Windows with Ruby 2.2.3 installed):

    ( o ) Logging in as ...
     ***  Cannot connect to www.geocaching.com:443: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

**Comment by steve8x8** [comment]
It might have been helpful to see the very first line of GeoToad output. I'm afraid this bug is platform-dependent.

**Comment by FriedrichFroebel** [comment]
Hope this is enough of the output (debug level 1):
```
-- Enter menu number, (s) to start, (R) to reset, or (Q) to exit --> s

D: Saved configuration
D: Saved configuration
( o ) To use this query in the future, type:
( o ) geotoad.rb --delimiter='|' --distanceMax=50 --format='html' --includeDisabled --out
put='C:/Geotoad/Dateien/test' --queryType=user 'test'

( - ) Setting debug level to 1
D: Debug level set to 1
D: Internally using distance 50.0 miles.
( - ) Thank you for using a released version of GeoToad.
( - ) Report bugs or suggestions at https://github.com/steve8x8/geotoad/
( - ) Please include verbose output (-v) without passwords in the bug report.
------------------------------------------------------------------------------
( o ) Templates: C:/Geocaching/Geotoad/lib/../templates
( - )     52 templates total
( o ) Dictionary: C:/Users/Geocaching/.geotoad/mapping.yaml
( - )   1172 WID->GUID mappings total
------------------------------------------------------------------------------
( - ) Cache directory: C:/Users/Geocaching/.geotoad/cache
( o ) Logging in as **
D: login called for user=** pass=**********
D: setting local expiry to 1
D: cachefile: C:/Users/Geocaching/.geotoad/cache/www.geocaching.com/login/default.aspx
D: local cache is 16478 (> 1) sec old
D: Fetching URL [https://www.geocaching.com/login/default.aspx]
 ***  Cannot connect to www.geocaching.com:443: SSL_connect returned=1 errno=0 state=SSLv3 re
ad server certificate B: certificate verify failed
D: 1 download errors so far, will try until 3
D: Fetching URL [https://www.geocaching.com/login/default.aspx]
 ***  Cannot connect to www.geocaching.com:443: SSL_connect returned=1 errno=0 state=SSLv3 re
ad server certificate B: certificate verify failed
D: 2 download errors so far, will try until 3
D: Fetching URL [https://www.geocaching.com/login/default.aspx]
 ***  Cannot connect to www.geocaching.com:443: SSL_connect returned=1 errno=0 state=SSLv3 re
ad server certificate B: certificate verify failed
D: 3 download errors so far, maximum reached
D: Fetching URL [https://www.geocaching.com/login/default.aspx]
 ***  Cannot connect to www.geocaching.com:443: SSL_connect returned=1 errno=0 state=SSLv3 re
ad server certificate B: certificate verify failed
( - ) Offline mode: not fetching https://www.geocaching.com/login/default.aspx
C:/Pascal/Geocaching/Geotoad/328/lib/shadowget.rb:257:in `fetchRemote': undefined method `len
gth' for nil:NilClass (NoMethodError)
        from C:/Geocaching/Geotoad/328/lib/shadowget.rb:169:in `fetch'
        from C:/Geocaching/Geotoad/328/lib/auth.rb:134:in `getLoginCookie'
        from C:/Geocaching/Geotoad/328/lib/auth.rb:25:in `login'
        from C:/Geocaching/Geotoad/328/geotoad.rb:330:in `downloadGeocacheList'
        from C:/Geocaching/Geotoad/328/geotoad.rb:1042:in `<main>'
```
Seems like it has something in common with https://github.com/steve8x8/geotoad/issues/329

**Comment by steve8x8** [comment]
To be continued in Issue #329. Closing here.
